# MobileExtra - 移动端实时帧外插与空洞补全系统
# Conda环境配置文件
# 使用方法: conda env create -f environment.yml

name: mobile_interpolation

channels:
  - pytorch
  - nvidia  
  - conda-forge
  - defaults

dependencies:
  # ===================
  # Python基础环境
  # ===================
  - python=3.9.*
  
  # ===================
  # 核心深度学习框架 (通过conda安装获得更好的优化)
  # ===================
  
  # PyTorch生态系统 (CUDA 11.8)
  - pytorch=2.1.*
  - torchvision=0.16.*
  - torchaudio=2.1.*
  - pytorch-cuda=11.8
  
  # ===================
  # 科学计算基础 (conda优化版本)
  # ===================
  
  # NumPy (Intel MKL优化)
  - numpy=1.24.*
  
  # SciPy
  - scipy=1.11.*
  
  # ===================
  # 图像处理库 (conda版本更稳定)
  # ===================
  
  # OpenCV
  - opencv=4.8.*
  
  # Pillow
  - pillow=10.0.*
  
  # ===================
  # 数据存储与I/O
  # ===================
  
  # Zarr
  - zarr=2.15.*
  
  # HDF5
  - h5py=3.9.*
  
  # OpenEXR (conda安装避免编译问题)
  - openexr=3.1.*
  
  # ImageIO
  - imageio=2.31.*
  
  # ===================
  # 可视化
  # ===================
  
  # Matplotlib
  - matplotlib=3.7.*
  
  # Seaborn
  - seaborn=0.12.*
  
  # ===================
  # 系统工具
  # ===================
  
  # tqdm
  - tqdm=4.65.*
  
  # psutil
  - psutil=5.9.*
  
  # ===================
  # 配置和文件处理
  # ===================
  
  # PyYAML
  - pyyaml=6.0.*
  
  # ===================
  # Jupyter支持
  # ===================
  
  - jupyter=1.0.*
  - ipywidgets=8.1.*
  
  # ===================
  # 代码质量工具
  # ===================
  
  - black=23.*
  - flake8=6.0.*
  
  # ===================
  # 通过pip安装的包
  # ===================
  - pip=23.*
  - pip:
    # PyTorch Lightning
    - pytorch-lightning>=2.0.0,<2.2.0
    
    # 高性能计算
    - opencv-contrib-python>=4.8.0,<4.10.0
    
    # 模型部署和优化
    - onnx>=1.14.0,<1.16.0
    - onnxruntime>=1.15.0,<1.17.0
    - tensorflow>=2.13.0,<2.16.0
    
    # 配置和参数处理
    - ConfigArgParse>=1.5.0,<1.8.0
    - pydantic>=1.10.0,<2.6.0
    
    # 性能监控
    - memory-profiler>=0.60.0,<0.62.0
    - rich>=13.0.0,<14.0.0
    
    # 实验跟踪
    - wandb>=0.15.0,<0.17.0
    - tensorboard>=2.13.0,<2.16.0
    
    # 测试框架
    - pytest>=7.4.0,<8.0.0
    - pytest-cov>=4.1.0,<5.0.0
    
    # 类型检查
    - mypy>=1.5.0,<1.8.0
    
    # 异步支持
    - aiofiles>=23.0.0,<24.0.0
    
    # 网络请求
    - requests>=2.31.0,<2.32.0
    
    # 日期处理
    - python-dateutil>=2.8.0,<2.10.0
    
    # 文档生成
    - sphinx>=7.0.0,<8.0.0
    - sphinx-rtd-theme>=1.3.0,<2.1.0
    
    # 代码重构
    - rope>=1.9.0,<1.12.0
    
    # 模型量化 (可选)
    - neural-compressor>=2.2.0,<2.5.0
    
    # 平台特定依赖
    - coremltools>=7.0.0,<7.1.0; sys_platform == "darwin"